### ISSUE TITLE
Не могу вытянуть image

### ISSUE THREAD

**Issue by litnimax** [litnimax/odoo_asterisk#8]
ansible-container build:

```
Building service...	project=deploy service=asterisk
Traceback (most recent call last):
  File "/usr/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 399, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 702, in conductorcmd_build
    cur_image_id = engine.pull_image_by_tag(service['from'])
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/docker/engine.py", line 618, in pull_image_by_tag
    raise exceptions.AnsibleContainerException("Failed to pull {}: {}".format(image, str(exc)))
container.exceptions.AnsibleContainerException: Failed to pull asterisk: 404 Client Error: Not Found ("pull access denied for asterisk, repository does not exist or may require 'docker login'")
Conductor terminated. Cleaning up.	command_rc=1 conductor_id=6f0761362436002c2fe8f6102c5bf02d453853d04db715c1d1e4cac1ec75dd8f save_container=False
ERROR	Conductor exited with status 1
```

**Comment by litnimax** [comment]
А вот from:   dougbtv/asterisk вытянул...

**Comment by litnimax** [comment]
А вот встали на from:broker

```
container.exceptions.AnsibleContainerException: Failed to pull broker: 404 Client Error: Not Found ("pull access denied for broker, repository does not exist or may require 'docker login'")
Conductor terminated. Cleaning up.	command_rc=1 conductor_id=261a1e9cb689d32f65e6ef7706b9c099095c70a9af99e8e3e6d87f32d550b8c4 save_container=False
ERROR	Conductor exited with status 1
```

Надо сделать ansible-container init и конвертировать Dockerfile построения брокера.
